WARNING | 2024-08-12 10:09:27,362 | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "C:\Users\Karpov\PycharmProjects\pythonProject1\module_12_4.py", line 75, in test_run
    runner = Runner(23)
             ^^^^^^^^^^
  File "C:\Users\Karpov\PycharmProjects\pythonProject1\module_12_4.py", line 10, in __init__
    raise TypeError(f'Имя может быть только числом, передано {type(name).__name__}')
TypeError: Имя может быть только числом, передано int
WARNING | 2024-08-12 10:09:27,363 | Неверная скорость для Runner
Traceback (most recent call last):
  File "C:\Users\Karpov\PycharmProjects\pythonProject1\module_12_4.py", line 63, in test_walk
    runner = Runner("Runner", -5)
             ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Karpov\PycharmProjects\pythonProject1\module_12_4.py", line 15, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
